### ISSUE TITLE
3M doesn't provide author for some books. We could find this info but don't.

### ISSUE THREAD

**Issue by gwendolen** [NYPL-Simplified/server_core#17]
_From @leonardr on August 20, 2015 15:53_

A large number of 3M books (at least 170 in NYPL collection) have no author listed. This is because 3M doesn't list an author. Some of these are compilations, but a lot of them are just regular books with no author listed. This makes them show up first in lists of books sorted by author.

The metadata wrangler can fix this. We have an ISBN for most of these books. We can use that to look up author information from OCLC.

A band-aid is to set Edition.author to 'Unknown' whenever we would otherwise set it to the empty string. That would hide the authorless books deep in the list.

_Copied from original issue: NYPL/Simplified-iOS#210_

**Comment by leonardr** [comment]
The underlying problems should be double-fixed at this point, but I'll need some time to make sure that the problem goes away naturally as our scripts run.

**Comment by leonardr** [comment]
This problem is not fixed, because the data just isn't there. These books are anthologies or other books that don't have an "author" role, and rather than giving us the roles (as Overdrive does) or treating the editor of an anthology as the "author" (as we present it to patrons), 3M just says the book has no author.

There is a path to getting accurate information and it goes through the metadata wrangler. 3M gives us an ISBN. When we ask the metadata wrangler about a book, the metadata wrangler will look up that ISBN. We can have the metadata wrangler fill in author information from OCLC Linked Data if that data is missing from the primary data source for the Edition (3M in this case).

As an example, the ISBN for "Dark Eros" (dptg8g9) is 9781429954310. Looking up that ISBN in OCLC Linked Data will let us get Reginald Martin as the author, which is not 100% accurate but is good enough for our purposes, and certainly better than nothing.

There's a slight problem in that the `contributions` table maps Contributor to Edition. I think it would be more accurate to map Contributor to Identifier (as we do with Subject, Equivalency, Measurement, etc.) and then figure everything out when we're deciding what string to display as `Work.author` and `Work.sort_author`. But we can fix the immediate problem without making this large change.

**Comment by leonardr** [comment]
I'm reopening this due to some problems which I think need to be addressed by the refactoring and which prevent the script from working.

The immediate problem is that LinkedDataCoverageProvider.process_item() calls metadata.apply(edition) even when metadata is None. LDCP.process_oclc_edition() returns None for metadata when it believes there's no work to do. It does this "If this OCLC Number didn't tell us about any ISBNs we didn't already know, and there is no description."

The first time we look up a book, it's true that a lack of new ISBNs means there's no work to do. But when we come back and redo the work to fix something (as we're doing here), we don't expect any of the ISBNs to be new, but we want the data anyway.

I think the determination of "is there work to do" should happen within process_item(), after process_oclc_edition() returns metadata. If there is no existing edition, and the metadata is basically empty, then don't create a new edition just to hold no information. If there is an existing edition, we should always reapply the metadata, even if it doesn't seem to hold anything new.

**Comment by leonardr** [comment]
I put my change to the 3M fix script in the branch https://github.com/NYPL-Simplified/metadata_wrangler/tree/fix-3m-author-fix-script

**Comment by jce1028** [comment]
I know this is not the right place to introduce this but going forward, we should consider reporting the metadata that is actually packaged in the ePub spine item with the book as a source of info.  Luckily, as readers read a book we could post the books metadata from the spine item of the book.  This can literally be gathered in the background by the client (albeit with some work) sense is has the only functionality to decrypt the book and parse the spine item.  Not something we want to do as part of this particular ticket but I thought relevant to the discussion.
  See spine item specs below.

http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.2.2

http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm

**Comment by leonardr** [comment]
James, I filed your comment as a standalone issue, https://github.com/NYPL-Simplified/Simplified/issues/47
